apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args:
            - redis-server
            - --save
            - "60"
            - "1"
            - --appendonly
            - "yes"
            - --replicaof
            - redis-master
            - "6379"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-slave-data
              mountPath: /data
      volumes:
        - name: redis-slave-data
          persistentVolumeClaim:
            claimName: redis-slave-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
spec:
  selector:
    app: redis-slave
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
